Updated configs of `Lefthook`
yamada-ui/yamada-theme pull request #12
Opened 2024-07-23 15:10 UTC by koralle

## Description

Updated configs of `Lefthook`.

## Is this a breaking change (Yes/No):

No

## Additional Information

To remove leftover `husky` settings, please run the following commands:

```bash
rm -rf .husky
git config --unset core.hooksPath
```

2024-07-24 10:52 UTC, 108yen requested changes

2024-07-24 10:52 UTC, 108yen commented on lefthook.yaml
> +        pnpm eslint {staged_files} --max-warnings=0 --fix
Please remove `--fix`

2024-07-24 11:29 UTC, 108yen commented
@koralle 
By the way, don't you have `spellcheck` set up?

2024-07-24 14:34 UTC, 108yen submitted a review, later dismissed

2024-07-25 16:36 UTC, koralle commented
> @koralle By the way, don't you have `spellcheck` set up?

@108yen 

Sorry. I added `spellcheck` command to `pre-commit` hook now.

2024-07-25 22:56 UTC, 108yen approved these changes

2024-07-26 14:57 UTC, hirotomoyamada approved these changes

2024-07-26 14:57 UTC, merged