Updated node version and pnpm
yamada-ui/yamada-theme pull request #13
Opened 2024-07-26 11:05 UTC by hirotomoyamada

## Description

Updated node version and pnpm.

## Is this a breaking change (Yes/No):

No

2024-07-26 14:26 UTC, koralle submitted a review, later dismissed

2024-07-26 14:26 UTC, koralle commented on package.json
> +  "packageManager": "pnpm@9.6.0",
@hirotomoyamada 

> The hash is optional but strongly recommended as a security practice. 

See: https://github.com/nodejs/corepack/blob/main/README.md#when-authoring-packages

2024-07-26 15:04 UTC, 108yen requested changes
Remove the `version` listed here. It conflicts with the `packageManeger` version.
https://github.com/yamada-ui/yamada-theme/blob/941f76192633eade405d01afc8e2516a25ff7295/.github/composite-actions/install/action.yml#L9-L10

2024-07-29 05:33 UTC, hirotomoyamada commented on package.json
> +  "packageManager": "pnpm@9.6.0",
Fixed.

2024-07-29 05:33 UTC, hirotomoyamada commented
@108yen 

Fixed.

2024-07-29 05:38 UTC, 108yen approved these changes

2024-07-29 06:53 UTC, merged